apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ${DOCKER_USERNAME}/exam-app:${IMAGE_TAG}
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
